export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const RECEIVE_PRODUCTS_SUCCESS = 'RECEIVE_PRODUCTS_SUCCESS'
export const RECEIVE_PRODUCTS_FAIL = 'RECEIVE_PRODUCTS_FAIL'
